# Generated by Django 4.2.6 on 2023-10-19 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CupomDesconto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=8, unique=True)),
                ("desconto", models.FloatField()),
                ("usos", models.IntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="pedido",
            name="data",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 19, 22, 57, 32, 225781)
            ),
        ),
    ]
