# Generated by Django 4.2.6 on 2023-10-19 23:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0002_cupomdesconto_alter_pedido_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="cupom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pedido.cupomdesconto",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="data",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 19, 23, 3, 16, 185382)
            ),
        ),
    ]
